SELECT SUBSTR(PHONE_NUMBER,1,3) OPERATOR,COUNT(*) TOTAL FROM HR.EMPLOYEES GROUP BY SUBSTR(PHONE_NUMBER,1,3);

SELECT * FROM (SELECT SUBSTR(T1.PHONE_NUMBER, 1, 3) A
FROM HR.employees T1
JOIN HR.employees T2
ON T1.PHONE_NUMBER LIKE SUBSTR(T2.PHONE_NUMBER, 1, 3) || '%' GROUP BY T1.PHONE_NUMBER) B PIVOT
(COUNT(*) FOR A IN(515,590,603,011,650));